backend:
    name: git-gateway
    branch: master

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
    - label: "Pages"
      name: "pages"
      files:
        - label: "Home Page"
          name: "home"
          file: "src/content/_index.md"
          fields:
            - { label: Title, name: title, widget: string }
            - { label: Image, name: image, widget: image }
